name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy config.yaml from secret
        run: 'echo BOT_CONFIG > config/config.yaml'
        shell: bash
        env:
          BOT_CONFIG: ${{ secrets.BOT_CONFIG }}

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Deploy App to App Engine
      - name: Deploy
        run: 'gcloud app deploy --quiet'